data:
  batch_size: 28
  images_home: /home/xavier_holt/data/image/segm/
  instances_home: /home/xavier_holt/data/image/dfdc
  size: [576, 1024] # [416, 768]
loss:
  kwargs:
    pos_weight: [0.25]
  type: BCEWithLogitsLoss
model:
  kwargs:
    advprop: True
    num_classes: 1
  type: efficientnet-b3
optim:
  kwargs:
    lr: 5.0e-06
  type: Adam
optim_scheduler:
  type: ExponentialLR
  kwargs:
    gamma: 0.99
trainer:
    gpus: 4
    use_amp: True
    distributed_backend: ddp
    train_percent_check: 0.03
    max_epochs: 100
early_stopping:
  monitor: val_loss_weighted
  patience: 10
  mode: min
image_scales: [1., 1., .75, .75, .5, .25]
aug:
  prob: 0.5
  level: 2
  
