data:
  batch_size: 192
  images_home: /home/xavier_holt/tensorflow_datasets/faces/
  instances_home: /home/xavier_holt/tensorflow_datasets/ts_im/
  size: [256, 256]
loss:
  kwargs:
    pos_weight: [0.15]
  type: BCEWithLogitsLoss
model:
  kwargs:
    advprop: True
    num_classes: 1
  type: efficientnet-b4
optim:
  kwargs:
    lr: 3.0e-05
  type: Adam
optim_scheduler:
  type: ExponentialLR
  kwargs:
    gamma: 0.99
trainer:
    gpus: 4
    use_amp: True
    distributed_backend: ddp
    max_epochs: 100
early_stopping:
  monitor: val_loss_weighted
  patience: 10
  mode: min
aug:
  prob: 0.5
  level: 2
