data:
  batch_size: 24
  images_home: /home/xavier_holt/tensorflow_datasets/faces/
  instances_home: /home/xavier_holt/tensorflow_datasets/ts_im/
  size: [256, 256]
loss:
  kwargs:
    pos_weight: [0.1]
  type: BCEWithLogitsLoss
model:
  kwargs:
    advprop: True
    num_classes: 1
  frame_kwargs:
    conv_channels: 256
    n_layers: 3

  type: efficientnet-b4
optim:
  kwargs:
    lr: 5.0e-06
  type: Adam
optim_scheduler:
  type: ExponentialLR
  kwargs:
    gamma: 0.99
trainer:
    gpus: 4
    use_amp: True
    distributed_backend: ddp
    max_epochs: 100
    num_sanity_val_steps: 0
early_stopping:
  monitor: val_loss_weighted
  patience: 10
  mode: min
aug:
  prob: 0.5
  level: 2

frame_mode: True